package views;

import data.Persistencia;
import domain.Marca;
import domain.Sucursal;
import domain.Vehiculo;
import domain.VehiculoCombustible;
import domain.VehiculoElectrico;
import domain.VehiculoTipo;
/**
 *
 * @author gabriel
 */
public class IngresarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form IngresarVehiculo
     */
    public IngresarVehiculo() {
        initComponents();

        GuardarBtn.addActionListener(evt -> guardarVehiculo());

        TipoComboBox.addActionListener(
            e -> actualizarCamposTipo()
        );

        actualizarCamposTipo();
    }
    
    
    
private void guardarVehiculo(){

    String patente = PatenteTxt.getText();
    String marcaNombre = MarcaTxt.getText();
    String pais = PaisOrigenTxt.getText();
    String modelo = ModeloTxt.getText();

    int anio = Integer.parseInt(AnioTxt.getText());
    double capacidad = Double.parseDouble(CapCargaTxt.getText());

    // OBTENER TIPO DESDE COMBO
    String tipoSeleccionado =
            (String) TipoComboBox.getSelectedItem();

    VehiculoTipo tipo =
            VehiculoTipo.valueOf(tipoSeleccionado);

    // OBTENER SUCURSAL DESDE COMBO
    String codigoSucursal =
            (String) SucursalComboBox.getSelectedItem();

    Sucursal sucursal =
            Persistencia.getSucursales()
            .stream()
            .filter(s -> s.getCodigo().equals(codigoSucursal))
            .findFirst()
            .orElse(null);

    Marca marca = new Marca(marcaNombre, pais);

    Vehiculo vehiculo;

    if(tipo == VehiculoTipo.ELECTRICO){

        int kwhBase =
                Integer.parseInt(KwhBaseTxt.getText());

        vehiculo = new VehiculoElectrico(
                patente,
                marca.getNombre(),
                modelo,
                anio,
                capacidad,
                sucursal,
                kwhBase
            );

    } else {

        double kmPorLitro =
                Double.parseDouble(KmPorLitroTxt.getText());

        double litrosExtra =
                Double.parseDouble(LitrosExtraTxt.getText());

        vehiculo = new VehiculoCombustible(
                patente,
                marca.getNombre(),
                modelo,
                anio,
                capacidad,
                sucursal,
                kmPorLitro,
                litrosExtra
            );
        }

        Persistencia.agregarVehiculo(vehiculo);

        System.out.println("Vehiculo guardado correctamente");
    }    

    private void actualizarCamposTipo(){

        String tipo =
                (String) TipoComboBox.getSelectedItem();

        if(tipo.equals("ELECTRICO")){

            ElectricoLbl.setVisible(true);
            KwhBaseLbl.setVisible(true);
            KwhBaseTxt.setVisible(true);

            
            CombustibleLbl.setVisible(false);
            KmPorLitroLbl.setVisible(false);
            KmPorLitroTxt.setVisible(false);

            LitrosExtraLbl.setVisible(false);
            LitrosExtraTxt.setVisible(false);

        } else {

            ElectricoLbl.setVisible(false);
            KwhBaseLbl.setVisible(false);
            KwhBaseTxt.setVisible(false);

            CombustibleLbl.setVisible(true);
            KmPorLitroLbl.setVisible(true);
            KmPorLitroTxt.setVisible(true);

            LitrosExtraLbl.setVisible(true);
            LitrosExtraTxt.setVisible(true);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PatenteLbl = new javax.swing.JLabel();
        MarcaLbl = new javax.swing.JLabel();
        PaisOrigenLbl = new javax.swing.JLabel();
        ModeloLbl = new javax.swing.JLabel();
        AnioLbl = new javax.swing.JLabel();
        CapCargaLbl = new javax.swing.JLabel();
        SucursalLbl = new javax.swing.JLabel();
        TipoLbl = new javax.swing.JLabel();
        PatenteTxt = new javax.swing.JTextField();
        MarcaTxt = new javax.swing.JTextField();
        PaisOrigenTxt = new javax.swing.JTextField();
        ModeloTxt = new javax.swing.JTextField();
        AnioTxt = new javax.swing.JTextField();
        CapCargaTxt = new javax.swing.JTextField();
        GuardarBtn = new javax.swing.JButton();
        TipoComboBox = new javax.swing.JComboBox<>();
        SucursalComboBox = new javax.swing.JComboBox<>();
        KwhBaseLbl = new javax.swing.JLabel();
        LitrosExtraLbl = new javax.swing.JLabel();
        KmPorLitroLbl = new javax.swing.JLabel();
        KwhBaseTxt = new javax.swing.JTextField();
        ElectricoLbl = new javax.swing.JLabel();
        CombustibleLbl = new javax.swing.JLabel();
        KmPorLitroTxt = new javax.swing.JTextField();
        LitrosExtraTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("INGRESAR DATOS DEL VEHICULO");

        PatenteLbl.setText("Patente:");

        MarcaLbl.setText("Marca:");

        PaisOrigenLbl.setText("Pais de origen:");

        ModeloLbl.setText("Modelo:");

        AnioLbl.setText("Año:");

        CapCargaLbl.setText("Capaciddad de carga:");

        SucursalLbl.setText("Sucursal:");

        TipoLbl.setText("Tipo:");

        GuardarBtn.setText("Guardar");

        TipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELECTRICO", "COMBUSTIBLE" }));

        SucursalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUC01", "SUC02" }));

        KwhBaseLbl.setText("kwh Base:");

        LitrosExtraLbl.setText("Litros Extra:");

        KmPorLitroLbl.setText("km por Litro:");

        ElectricoLbl.setText("ELECTRICO");

        CombustibleLbl.setText("COMBUSTIBLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardarBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(ModeloLbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PaisOrigenLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MarcaLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PatenteLbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MarcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaisOrigenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnioLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(CapCargaLbl))
                                .addComponent(SucursalLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TipoLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapCargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SucursalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LitrosExtraLbl)
                                    .addComponent(KmPorLitroLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KmPorLitroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LitrosExtraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(KwhBaseLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(KwhBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 247, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(ElectricoLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CombustibleLbl)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatenteLbl)
                            .addComponent(AnioLbl)
                            .addComponent(PatenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarcaLbl)
                            .addComponent(CapCargaLbl)
                            .addComponent(MarcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapCargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaisOrigenLbl)
                            .addComponent(SucursalLbl)
                            .addComponent(PaisOrigenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SucursalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoLbl)
                            .addComponent(ModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeloLbl)
                            .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(ElectricoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KwhBaseLbl)
                            .addComponent(KwhBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(CombustibleLbl)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KmPorLitroLbl)
                            .addComponent(KmPorLitroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LitrosExtraLbl)
                            .addComponent(LitrosExtraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addComponent(GuardarBtn)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioLbl;
    private javax.swing.JTextField AnioTxt;
    private javax.swing.JLabel CapCargaLbl;
    private javax.swing.JTextField CapCargaTxt;
    private javax.swing.JLabel CombustibleLbl;
    private javax.swing.JLabel ElectricoLbl;
    private javax.swing.JButton GuardarBtn;
    private javax.swing.JLabel KmPorLitroLbl;
    private javax.swing.JTextField KmPorLitroTxt;
    private javax.swing.JLabel KwhBaseLbl;
    private javax.swing.JTextField KwhBaseTxt;
    private javax.swing.JLabel LitrosExtraLbl;
    private javax.swing.JTextField LitrosExtraTxt;
    private javax.swing.JLabel MarcaLbl;
    private javax.swing.JTextField MarcaTxt;
    private javax.swing.JLabel ModeloLbl;
    private javax.swing.JTextField ModeloTxt;
    private javax.swing.JLabel PaisOrigenLbl;
    private javax.swing.JTextField PaisOrigenTxt;
    private javax.swing.JLabel PatenteLbl;
    private javax.swing.JTextField PatenteTxt;
    private javax.swing.JComboBox<String> SucursalComboBox;
    private javax.swing.JLabel SucursalLbl;
    private javax.swing.JComboBox<String> TipoComboBox;
    private javax.swing.JLabel TipoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}